/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slate;

import slate.bases.MapBase;
import slate.maps.TestMap;

public class App {

    // Define the map to use
    MapBase current_map = new TestMap();

    public static void main(String[] args) {
        new App();
    }

    App() {
        // Pint the map introduction text
        System.out.println(current_map.getDescription());
        System.out.println(current_map.nav.getCurrentRoom().getRoomInfo());

        
        
    }
}
