/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slate;

import slate.bases.MapBase;
import slate.maps.TestMap;
import slate.parser.Command;

import static slate.parser.Commands.getInput;

public class App {
    //Player
    public Player player = Player.getInstance();

    // Define the map to use
    public MapBase current_map = new TestMap();

    public static void main(String[] args) {
        new App();
    }

    App() {

        // Pint the map introduction text
        System.out.println(current_map.getDescription());
        System.out.println(current_map.nav.getCurrentRoom().getRoomInfo());

        //Set starting inventory
        player.setFocused_inventory(current_map.nav.getCurrentRoom().getRoot_inventory());

        while (true) {
            Command[] comms = getInput();
            for (Command comm : comms) {
                comm.game = this;

                //If command is valid, execute it.
                if (comm.validate()) {
                    comm.execute();
                }

                //Handle running into guards
                if(current_map.nav.getCurrentRoom().getGuards().size()>0){
                    System.out.println("I ran into a guard, I'm lucky nobody has added any penalties to the game yet.");
                }
            }
        }
    }
}
